### ISSUE TITLE
Add option to replace files with hard or softlinks instead of just removing

### ISSUE THREAD

**Issue by quentinmit** [Canop/backdown#2]
Sometimes you still want to keep the duplicate files in the filesystem (e.g. because a file came from multiple overlapping torrents), but you could still save the disk space by replacing all the files with a hardlink.

**Comment by Canop** [comment]
That would be in a special session type, and you would apply this replacement to all duplicates, right ?

**Comment by quentinmit** [comment]
I'm not sure what you mean by "special session type", but yes, I would want this to apply to all duplicates. (Well, except one of course, since something has to remain as the target of the link)

**Comment by Canop** [comment]
ok, it's clear. I will think about it. Not sure there would be more than one user for this feature ^^

**Comment by quentinmit** [comment]
Hah, well, I think anyone who uses BitTorrent a fair amount would have this desire.

But perhaps as an even more generic feature, just provide an option to dump the list of duplicates in a machine readable form, so users could provide their own processing logic as desired.

**Comment by Canop** [comment]
This is a good idea too. I'll probably do both.

**Comment by Canop** [comment]
I created a new issue to separate both features: https://github.com/Canop/backdown/issues/3

**Comment by Canop** [comment]
Note: The implementation I'm doing for the links won't be for Windows. A different implementation is necessary for Windows and I can't properly test on this platform.
